### ISSUE TITLE
Add iOS platform fails when short name is used

### ISSUE THREAD

**Issue by dlredden** [dpa99c/cordova-plugin-firebasex#114]
I get the following error when trying to add the iOS platform. I traced the issue to the `<name />` tag in the config file. `<name>My App</name>` works just fine but, adding the `short` attribute causes this issue, i.e. `<name short="My App">My App</name>`.

```
Running command: pod install --verbose

[!] The `Pool League [Debug]` target overrides the `LD_RUNPATH_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-Pool League/Pods-Pool League.debug.xcconfig'. This can lead to problems with the CocoaPods installation

[!] The `Pool League [Release]` target overrides the `LD_RUNPATH_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-Pool League/Pods-Pool League.release.xcconfig'. This can lead to problems with the CocoaPods installation

Failed to install 'cordova-plugin-firebasex': Error: ENOENT: no such file or directory, open '/Users/dl/repos/LeagueCentral/platforms/ios/[object Object].xcodeproj/project.pbxproj'
    at Object.openSync (fs.js:436:3)
    at Object.readFileSync (fs.js:341:35)
    at pbxProject.parseSync (/Users/dl/repos/LeagueCentral/node_modules/xcode/lib/pbxProject.js:61:28)
    at Object.removeShellScriptBuildPhase (/Users/dl/repos/LeagueCentral/plugins/cordova-plugin-firebasex/scripts/ios/helper.js:87:22)
    at /Users/dl/repos/LeagueCentral/plugins/cordova-plugin-firebasex/scripts/ios/after_plugin_install.js:8:16
    at /Users/dl/repos/LeagueCentral/plugins/cordova-plugin-firebasex/scripts/ios/helper.js:19:13
    at /Users/dl/repos/LeagueCentral/plugins/cordova-plugin-firebasex/scripts/lib/utilities.js:27:11
    at Parser.<anonymous> (/Users/dl/repos/LeagueCentral/node_modules/xml2js/lib/parser.js:303:18)
    at Parser.emit (events.js:182:13)
    at SAXParser.onclosetag (/Users/dl/repos/LeagueCentral/node_modules/xml2js/lib/parser.js:261:26)
ENOENT: no such file or directory, open '/Users/dl/repos/LeagueCentral/platforms/ios/[object Object].xcodeproj/project.pbxproj'
```

**Comment by dpa99c** [comment]
Fixed by PR #115 which will shortly be released in v6.0.8
