### ISSUE TITLE
Log Error does nothing

### ISSUE THREAD

**Issue by mariuszgola** [dpa99c/cordova-plugin-firebasex#131]
The method logError() returns a successful callback but does not report anything in Firebase.

**Comment by dpa99c** [comment]
As [shown here](https://github.com/dpa99c/cordova-plugin-firebasex/issues/40#issuecomment-510585354), `logError()` send the event to Firebase immediately - you can confirm this by monitoring the native console output - but the Firebase Console does not display the data immediately.

If you wish for realtime feedback in the Firebase Console, you [enable Firebase Analytics debugging](https://firebase.google.com/docs/analytics/debugview) on the native platform.

**Comment by mariuszgola** [comment]
Dave, I get all that. I checked the firebase console again today and still nothing. I also have the debug view enabled and the errors are not coming thru. 
logEvent works as expected. I may just end up using logEvent to track non-fatal exceptions.
 
Below is the output from logcat. 
I tried logError and logMessage followed by sendCrash.

`2019-09-05 08:52:47.311 16746-16923/com.assaabloy.technicalsupport D/FirebasePlugin: Starting Firebase plugin
2019-09-05 08:53:00.699 16746-16997/com.assaabloy.technicalsupport E/FirebasePlugin: FirebasePlugin :: logError
2019-09-05 08:54:46.934 17455-17624/? D/FirebasePlugin: Starting Firebase plugin
2019-09-05 08:55:01.892 17455-17751/? E/FirebasePlugin: FirebasePlugin :: logError
2019-09-05 08:55:02.064 17455-17455/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.assaabloy.technicalsupport, PID: 17455
    java.lang.RuntimeException: This is a crash
        at org.apache.cordova.firebase.FirebasePlugin$11.run(FirebasePlugin.java:534)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6688)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)`

Thank you
mariusz

**Comment by dpa99c** [comment]
OK, I will regression test this with v6.1.0 on Android using the example project and let you know the result

**Comment by mariuszgola** [comment]
Davne, I think it has something to do with my account linking, found some google results around this.


`2019-09-05 10:47:28.263 2059-2307/xxx.xxxxxxxxxxxx.technicalsupport E/Fabric: Failed to retrieve settings from https://settings.crashlytics.com/spi/v2/platforms/android/apps/xxxx.xxxxxx.technicalsupport/settings`


mariusz

**Comment by mariuszgola** [comment]
Solution for anyone with same issue: https://stackoverflow.com/a/49252648/54667
