### ISSUE TITLE
Error when adding ios platform

### ISSUE THREAD

**Issue by willxw8** [dpa99c/cordova-plugin-firebasex#152]
I put the GoogleService-Info.plist in the root folder, and add this node to config.xml:
        `<resource-file src="GoogleService-Info.plist"/>`
then run the command "cordova platform add ios", I get this error:

Error during processing of action! Attempting to revert...
Failed to install 'cordova-plugin-firebasex': CordovaError: Uh oh!
File already exists at destination "C:\DevelopmentGit\Stopfinder\stopfinderapp\cordova\platforms\ios\Stopfinder\Resources\GoogleService-Info.plist" for resource file specified by plugin cordova-plugin-firebasex in iOS platform
    at install (C:\DevelopmentGit\Stopfinder\stopfinderapp\cordova\platforms\ios\cordova\lib\plugman\pluginHandlers.js:64:23)
    at ActionStack.process (C:\DevelopmentGit\Stopfinder\stopfinderapp\cordova\node_modules\cordova-common\src\ActionStack.js:56:25)
    at PluginManager.doOperation (C:\DevelopmentGit\Stopfinder\stopfinderapp\cordova\node_modules\cordova-common\src\PluginManager.js:114:20)
    at PluginManager.addPlugin (C:\DevelopmentGit\Stopfinder\stopfinderapp\cordova\node_modules\cordova-common\src\PluginManager.js:144:17)
    at Api.addPlugin (C:\DevelopmentGit\Stopfinder\stopfinderapp\cordova\platforms\ios\cordova\Api.js:245:10)
    at handleInstall (C:\Users\Will\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:581:10)
    at C:\Users\Will\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:349:28
    at process._tickCallback (internal/process/next_tick.js:68:7)

If I delete the node from the config.xml, I can add the ios platform successfully, but the GoogleService-Info.plist file is not mine, it is a default placeholder from the plugin.

**Comment by dpa99c** [comment]
Do not add `<resource-file src="GoogleService-Info.plist"/>` to your `config.xml` - simply put the file in the root directory of the project and the plugin will pick it up.
