### ISSUE TITLE
ENOENT: no such file or directory, open './package.json'

### ISSUE THREAD

**Issue by fax1ty** [dpa99c/cordova-plugin-firebasex#233]
What exactly does this code do? I can't build the app because of it

https://github.com/dpa99c/cordova-plugin-firebasex/blob/087912424a76ce9d96c9e88af1f7224309bc3cf5/scripts/after_prepare.js#L72-L84

It leads to the following

```
Prepared android project successfully
Executing script found in plugin cordova-plugin-firebasex for hook "after_prepare": plugins/cordova-plugin-firebasex/scripts/after_prepare.js
ENOENT: no such file or directory, open './package.json'
Error: ENOENT: no such file or directory, open './package.json'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at Object.Utilities.parsePackageJson (/home/travis/build/eclipsesource/tabris-js-build-template/build/build/cordova/plugins/cordova-plugin-firebasex/scripts/lib/utilities.js:25:26)
    at parsePluginVariables (/home/travis/build/eclipsesource/tabris-js-build-template/build/build/cordova/plugins/cordova-plugin-firebasex/scripts/after_prepare.js:73:33)
    at module.exports (/home/travis/build/eclipsesource/tabris-js-build-template/build/build/cordova/plugins/cordova-plugin-firebasex/scripts/after_prepare.js:90:3)
    at runScriptViaModuleLoader (/home/travis/.tabris-cli/cordova/8.1.2/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:196:18)
    at runScript (/home/travis/.tabris-cli/cordova/8.1.2/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:172:16)
    at /home/travis/.tabris-cli/cordova/8.1.2/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:140:20
    at _fulfilled (/home/travis/.tabris-cli/cordova/8.1.2/node_modules/cordova/node_modules/q/q.js:854:54)
    at /home/travis/.tabris-cli/cordova/8.1.2/node_modules/cordova/node_modules/q/q.js:883:30
```

**Environment information**
- **Cordova CLI version:** cordova-8.1.2
- **Cordova platform version:** android platform version 3.2.1
- **Plugins & versions installed in project (including this plugin):** 

| Plugin Name | Plugin Link |
|-----------------------------------|-----------------------------------------------------------------|
| cordova-vk-auth | https://github.com/iRapoo/cordova-vk-auth.git |
| cordova-plugin-googleplus | https://github.com/EddyVerbruggen/cordova-plugin-googleplus.git |
| cordova-plugin-firebasex | https://github.com/dpa99c/cordova-plugin-firebasex.git |
| tabris-plugin-maps | https://github.com/fax1ty/tabris-plugin-maps.git |
| cordova-plugin-vibration | https://github.com/maxappsmobile/cordova-plugin-vibration.git |
| cordova-plugin-native-geolocation | https://github.com/fax1ty/cordova-plugin-native-geolocation.git |
| cordova-plugin-datepicker | https://github.com/fax1ty/cordova-plugin-datepicker.git |
| cordova-gallery-api | https://github.com/Collaborne/cordova-gallery-api.git |

**- Dev machine OS and version, e.g.:** Travis Cloud Build - Ubuntu 14.04.5 LTS

*Android build issue:*	
- **Node JS version:** v10.17.0 (npm v6.11.3)
- **Gradle version:** ¯\\\_(ツ)\_/¯
- **Target Android SDK version:** android-28

**Comment by Anarchid** [comment]
In my case the entire hook fails because it can't find any of the app or plugin xml files, nor the google-services config files for either android or ios.

It looks like this is because it addresses these paths without the directory prefix, e.g. expecting them to be in the current directory. Possibly a MacOS specific issue.

Hacking the hook to prefix `process.env['PWD']` to each of the file queries in Utilities.js fixes that, but i'm not sure it's a robust solution.

**Comment by fax1ty** [comment]
@dpa99c still
```Error: ENOENT: no such file or directory, open './package.json'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at Object.Utilities.parsePackageJson (/home/travis/build/eclipsesource/tabris-js-build-template/build/build/cordova/plugins/cordova-plugin-firebasex/scripts/lib/utilities.js:25:26)
    at parsePluginVariables (/home/travis/build/eclipsesource/tabris-js-build-template/build/build/cordova/plugins/cordova-plugin-firebasex/scripts/after_prepare.js:73:33)
    at module.exports (/home/travis/build/eclipsesource/tabris-js-build-template/build/build/cordova/plugins/cordova-plugin-firebasex/scripts/after_prepare.js:90:3)
    at runScriptViaModuleLoader (/home/travis/.tabris-cli/cordova/8.1.2/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:196:18)
    at runScript (/home/travis/.tabris-cli/cordova/8.1.2/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:172:16)
    at /home/travis/.tabris-cli/cordova/8.1.2/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:140:20
    at _fulfilled (/home/travis/.tabris-cli/cordova/8.1.2/node_modules/cordova/node_modules/q/q.js:854:54)
    at /home/travis/.tabris-cli/cordova/8.1.2/node_modules/cordova/node_modules/q/q.js:883:30
```

**Comment by dpa99c** [comment]
@fax1ty did you install the plugin off the master branch of this repo? 
This fix has not been released in an npm-published version yet. Please check you see the code changes from https://github.com/dpa99c/cordova-plugin-firebasex/commit/62e43910a0e683b88a1bf260a3211f18d94139fc in your installed version of the plugin.

Also looks to me as though you are using some wrapper around the Cordova CLI rather than invoking it directly (e.g. `cordova prepare`). If this is causing the cwd to resolve as a directory other than the Cordova project root, this would also cause such an error.

**Comment by fax1ty** [comment]
@dpa99c 
1) Here's how I add a plugin to an app
```xml
<plugin name="cordova-plugin-firebasex" source="https://github.com/dpa99c/cordova-plugin-firebasex.git">
    <variable name="ANDROID_PLAY_SERVIC....
 </plugin>
```

2) I'm using [Tabris](https://tabris.com/). Yes, `cordova prepare` command is not executed

**Comment by dpa99c** [comment]
> @dpa99c
> 
> 1. Here's how I add a plugin to an app
> 
> ```
> <plugin name="cordova-plugin-firebasex" source="https://github.com/dpa99c/cordova-plugin-firebasex.git">
>     <variable name="ANDROID_PLAY_SERVIC....
>  </plugin>
> ```

Looks fine but worth double-checking you see the code changes by the above commit in `/home/travis/build/eclipsesource/tabris-js-build-template/build/build/cordova/plugins/cordova-plugin-firebasex/scripts/lib/utilities.js`

> 2. I'm using [Tabris](https://tabris.com/). Yes, `cordova prepare` command is not executed

Could well be the cause of the issue if it causes cwd to resolve to a different directory.
This plugin is intended to work with the vanilla Cordova CLI and as such support for external build tools which wrap it such as this one is out of scope.

**Comment by fax1ty** [comment]
@dpa99c 
1) I can't see the downloaded plugins. No access :-(
2) They have [their own version](https://github.com/eclipsesource/tabris-plugin-firebase), but as I can see, they haven't changed anything with the paths
