### ISSUE TITLE
FirebasePlugin.java already exists

### ISSUE THREAD

**Issue by DilipDalwadi** [dpa99c/cordova-plugin-firebasex#238]
I used "@ionic-native/firebase-x": "^5.14.0" and "cordova-plugin-firebasex": "^6.1.0" in ionic v4 project before 12/11/2019 and i was able to generate android build successfully.

ionic version: **5.4.8**
node version: **v10.16.0**
npm version: **6.9.0**
cordova version: **9.0.0 (cordova-lib@9.0.1)**
Gradle version: **6.0.1**
java version: **openjdk version "1.8.0_222"**
OS: **Ubuntu 18.04**

But now when i am trying to remove android platform and add android platform again then it shows me below error:

`
Install start for "cordova-plugin-firebasex" on android.
Beginning processing of action stack for android project...
Error during processing of action! Attempting to revert...
Failed to install 'cordova-plugin-firebasex': CordovaError: Uh oh!
"/home/....../demoApp/platforms/android/app/src/main/java/org/apache/cordova/firebase/FirebasePlugin.java" already exists!
    at copyNewFile (/home/....../demoApp/platforms/android/cordova/lib/pluginHandlers.js:234:45)
    at install (/home/....../demoApp/platforms/android/cordova/lib/pluginHandlers.js:34:17)
    at ActionStack.process (/home/....../demoApp/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PluginManager.doOperation (/home/....../demoApp/node_modules/cordova-common/src/PluginManager.js:114:20)
    at PluginManager.addPlugin (/home/....../demoApp/node_modules/cordova-common/src/PluginManager.js:144:17)
    at /home/....../demoApp/platforms/android/cordova/Api.js:210:74
    at _fulfilled (/home/....../demoApp/platforms/android/cordova/node_modules/q/q.js:854:54)
    at /home/....../demoApp/platforms/android/cordova/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/home/....../demoApp/platforms/android/cordova/node_modules/q/q.js:816:13)
    at /home/....../demoApp/platforms/android/cordova/node_modules/q/q.js:877:14
`

Due to this error i can not run the application. Only white screen is displayed.

**Comment by dpa99c** [comment]
The error above is a Cordova project configuration issue, not an issue caused by this plugin.
It indicates Cordova has failed to deploy the plugin source files to the Android platform project since a file with that filepath already exists.
One possible explanation is you have both `cordova-plugin-firebase` and `cordova-plugin-firebasex` present in your project - that would cause such an error.
You can validate that this plugin works correctly using the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test)
