### ISSUE TITLE
Must Initialize Fabric before using singleton()

### ISSUE THREAD

**Issue by ir2pid** [dpa99c/cordova-plugin-firebasex#295]
The app crashes at launch.
this is occurs when calling this.firebasePlugin.logMessage("some message")

logcat:
```

2020-02-05 14:48:26.219 21405-21552/? E/AndroidRuntime: FATAL EXCEPTION: pool-13-thread-4
    Process: yy.zz.xx, PID: 21405
    java.lang.IllegalStateException: Must Initialize Fabric before using singleton()
        at io.fabric.sdk.android.c.a(SourceFile:301)
        at io.fabric.sdk.android.c.a(SourceFile:551)
        at com.crashlytics.android.a.e(SourceFile:191)
        at com.crashlytics.android.a.g(SourceFile:390)
        at com.crashlytics.android.a.a(SourceFile:221)
        at org.apache.cordova.firebase.FirebasePlugin$12.run(SourceFile:559)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by dpa99c** [comment]
You can validate that the `logMessage()` function works correctly in isolation by building and running the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test).

Possible causes are because `logMessage()` has been called before Crashlytics has been enabled if autoinit is disabled or another plugin is pulling in a conflicting version of the Crashlytics or Fabric SDKs.
