### ISSUE TITLE
Android Crashes on start: java.lang.NoSuchMethodError: No virtual method setTokenProvider(Lcom/google/firebase/internal/InternalTokenProvider;)

### ISSUE THREAD

**Issue by testanddeploy** [dpa99c/cordova-plugin-firebasex#410]
**Current behavior:**

App crashes on start:

LogCat shows this exception:

`java.lang.NoSuchMethodError: No virtual method setTokenProvider(Lcom/google/firebase/internal/InternalTokenProvider;)V in class Lcom/google/firebase/FirebaseApp; or its super classes (declaration of 'com.google.firebase.FirebaseApp' appears in /data/app/my.bundleid-5spqehnVvH30SZeVd1jNOw==/base.apk!classes2.dex)
        at com.google.firebase.auth.zzp.create(Unknown Source:4)
        at com.google.firebase.components.ComponentRuntime.lambda$new$0(com.google.firebase:firebase-components@@16.0.0:69)
        at com.google.firebase.components.ComponentRuntime$$Lambda$1.get(Unknown Source:4)
        at com.google.firebase.components.Lazy.get(com.google.firebase:firebase-components@@16.0.0:53)
        at com.google.firebase.components.ComponentRuntime.initializeEagerComponents(com.google.firebase:firebase-components@@16.0.0:158)
        at com.google.firebase.FirebaseApp.initializeAllApis(com.google.firebase:firebase-common@@19.3.0:563)
        at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@19.3.0:304)
        at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@19.3.0:268)
        at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@19.3.0:253)
        at com.google.firebase.provider.FirebaseInitProvider.onCreate(com.google.firebase:firebase-common@@19.3.0:51)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1940)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1915)
        at com.google.firebase.provider.FirebaseInitProvider.attachInfo(com.google.firebase:firebase-common@@19.3.0:45)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6930)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6477)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6381)
        at android.app.ActivityThread.access$1300(ActivityThread.java:248)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1830)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7266)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)`

If uninstall plugin it starts normally

I have pushed android min version sdk to 21 with 

`    <preference name="android-minSdkVersion" value="21" />`

An alternative I have installed the cordova-plugin-enable-multidex. with the same result

**Expected behavior:**

Apps start normally

**Environment information**

- Cordova CLI version 
	- 9.0.0
- Cordova platform version
	- 8.1.0
- Plugins & versions installed in project (including this plugin)
    - `com.darktalker.cordova.screenshot 0.1.5 "Screenshot"
cordova-custom-config 5.1.0 "cordova-custom-config"
cordova-plugin-advanced-http 2.4.1 "Advanced HTTP plugin"
cordova-plugin-androidx 1.0.2 "cordova-plugin-androidx"
cordova-plugin-androidx-adapter 1.1.1 "cordova-plugin-androidx-adapter"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-firebasex 9.1.1 "Google Firebase Plugin"
cordova-plugin-inappbrowser 3.2.0 "InAppBrowser"
cordova-plugin-ionic-webview 4.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-network-information 2.0.2-dev "Network Information"
cordova-plugin-screen-orientation 3.0.2 "Screen Orientation"
cordova-plugin-splashscreen 5.0.3 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-plugin-x-socialsharing 5.6.8 "SocialSharing"
cordova-sqlite-storage 5.0.0 "Cordova sqlite storage plugin - cordova-sqlite-storage plugin version"
cordova-wheel-selector-plugin 1.0.0 "Cordova Wheel Selector Plugin"
es6-promise-plugin 4.2.2 "Promise"
ionic-plugin-keyboard 2.2.1 "Keyboard"
`
- Dev machine OS and version, e.g.
    - OSX     
- Device details
    - Samsung Galaxy J5 Android 9

Any idea about this problem?

**Comment by dpa99c** [comment]
Please try building and running the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) to eliminate the possibility of conflicts with other plugins in your project.

Also if you are specifying custom versions of the Android Firebase SDK components via [plugin variables](https://github.com/dpa99c/cordova-plugin-firebasex#android-only) then make sure that the Firestore and Firebase Auth components are the [latest versions](https://firebase.google.com/support/release-notes/android) - see [this SO post](https://stackoverflow.com/questions/56099945/java-lang-nosuchmethoderror-no-virtual-method-settokenprovider) for reference.

**Comment by testanddeploy** [comment]
Hi @dpa99c thanks for your response.

Hi have no customized the version of firebase sdk, I have installed the library with:

`ionic cordova plugin add cordova-plugin-firebasex`

And I have the last versions of firestore and firebase Auth, this is my project.properties:

`# Project target.
target=android-28
android.library.reference.1=CordovaLib
android.library.reference.2=app
cordova.system.library.1=androidx.annotation:annotation:1.0.0
cordova.system.library.2=androidx.legacy:legacy-support-v4:1.0.0
cordova.system.library.3=com.squareup.okhttp3:okhttp-urlconnection:3.10.0
cordova.gradle.include.1=cordova-plugin-enable-multidex/app-build.gradle
cordova.gradle.include.2=cordova-plugin-firebasex/app-build.gradle
cordova.system.library.4=com.google.android.gms:play-services-tagmanager:17.0.0
cordova.system.library.5=com.google.android.gms:play-services-auth:18.0.0
cordova.system.library.6=com.google.firebase:firebase-analytics:17.4.0
cordova.system.library.7=com.google.firebase:firebase-messaging:20.1.6
cordova.system.library.8=com.google.firebase:firebase-config:19.1.4
cordova.system.library.9=com.google.firebase:firebase-perf:19.0.7
cordova.system.library.10=com.google.firebase:firebase-auth:19.3.1
cordova.system.library.11=com.google.firebase:firebase-inappmessaging-display:19.0.6
cordova.system.library.12=com.google.firebase:firebase-firestore:21.4.3
cordova.system.library.13=com.crashlytics.sdk.android:crashlytics:2.10.1
cordova.system.library.14=com.crashlytics.sdk.android:crashlytics-ndk:2.1.1
cordova.system.library.15=com.google.code.gson:gson:2.8.6`

Any wrong version?

**Comment by dpa99c** [comment]
Please try building and running the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) to eliminate the possibility of conflicts with other plugins in your project.

**Comment by testanddeploy** [comment]
Hi @dpa99c ,

I have tried the example project and **works fine on the same device/machine.**

Then I uninstalled each plugin of my project until my `cordova plugin list` be the same of the example project.

This is now, my cordova plugin list result

`cordova-plugin-androidx 1.0.2 "cordova-plugin-androidx"
cordova-plugin-androidx-adapter 1.1.1 "cordova-plugin-androidx-adapter"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-enable-multidex 0.2.0 "Enable Multidex"
cordova-plugin-firebasex 9.1.1 "Google Firebase Plugin"
cordova-plugin-ionic-webview 4.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.3 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-whitelist 1.3.4 "Whitelist"
`

And this the result of your example project:

`cordova-custom-config 5.1.0 "cordova-custom-config"
cordova-plugin-androidx 1.0.2 "cordova-plugin-androidx"
cordova-plugin-androidx-adapter 1.1.1 "cordova-plugin-androidx-adapter"
cordova-plugin-customfcmreceiver 1.0.0 "Custom FCM Receiver"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 1.3.2-dev "Notification"
cordova-plugin-enable-multidex 0.2.0 "Enable Multidex"
cordova-plugin-firebasex 9.1.1 "Google Firebase Plugin"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.4 "Whitelist"
`


This is the android platform project properties of my project:

# Project target.
target=android-28
android.library.reference.1=CordovaLib
android.library.reference.2=app
cordova.system.library.1=androidx.annotation:annotation:1.0.0
cordova.gradle.include.1=cordova-plugin-firebasex/app-build.gradle
cordova.system.library.2=com.google.android.gms:play-services-tagmanager:17.0.0
cordova.system.library.3=com.google.android.gms:play-services-auth:18.0.0
cordova.system.library.4=com.google.firebase:firebase-analytics:17.4.0
cordova.system.library.5=com.google.firebase:firebase-messaging:20.1.6
cordova.system.library.6=com.google.firebase:firebase-config:19.1.4
cordova.system.library.7=com.google.firebase:firebase-perf:19.0.7
cordova.system.library.8=com.google.firebase:firebase-auth:19.3.1
cordova.system.library.9=com.google.firebase:firebase-inappmessaging-display:19.0.6
cordova.system.library.10=com.google.firebase:firebase-firestore:21.4.3
cordova.system.library.11=com.crashlytics.sdk.android:crashlytics:2.10.1
cordova.system.library.12=com.crashlytics.sdk.android:crashlytics-ndk:2.1.1
cordova.system.library.13=com.google.code.gson:gson:2.8.6
cordova.gradle.include.2=cordova-plugin-enable-multidex/app-build.gradle


And this is the logcat of my app every start when it crashes:

```
2020-05-25 15:05:42.416 7909-7909/com.myappapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.myapp.app, PID: 7909
    java.lang.NoSuchMethodError: No virtual method setTokenProvider(Lcom/google/firebase/internal/InternalTokenProvider;)V in class Lcom/google/firebase/FirebaseApp; or its super classes (declaration of 'com.google.firebase.FirebaseApp' appears in /data/app/com.myapp.app-NY2l7gSuOGTVACqNndiwFQ==/base.apk!classes3.dex)
        at com.google.firebase.auth.zzp.create(Unknown Source:4)
        at com.google.firebase.components.ComponentRuntime.lambda$new$0(com.google.firebase:firebase-components@@16.0.0:69)
        at com.google.firebase.components.ComponentRuntime$$Lambda$1.get(Unknown Source:4)
        at com.google.firebase.components.Lazy.get(com.google.firebase:firebase-components@@16.0.0:53)
        at com.google.firebase.components.ComponentRuntime.initializeEagerComponents(com.google.firebase:firebase-components@@16.0.0:158)
        at com.google.firebase.FirebaseApp.initializeAllApis(com.google.firebase:firebase-common@@19.3.0:563)
        at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@19.3.0:304)
        at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@19.3.0:268)
        at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@19.3.0:253)
        at com.google.firebase.provider.FirebaseInitProvider.onCreate(com.google.firebase:firebase-common@@19.3.0:51)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1940)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1915)
        at com.google.firebase.provider.FirebaseInitProvider.attachInfo(com.google.firebase:firebase-common@@19.3.0:45)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6930)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6477)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6381)
        at android.app.ActivityThread.access$1300(ActivityThread.java:248)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1830)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7266)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
2020-05-25 15:06:11.992 7909-7956/com.myampere.app E/FirebaseInstanceId: Token retrieval failed: SERVICE_NOT_AVAILABLE
```


any idea or help?

**Comment by dpa99c** [comment]
If the example project works OK, then the problem must be specific to your project.
If you haven't already, try removing and re-adding the Android platform project: 

    cordova platform rm android --nosave && cordova platform add android --nosave

If that doesn't help, it's a question of comparing what's different in your project vs the example project.

Closing this as it seems specific to you rather than a general plugin bug which is likely to affect other users.

**Comment by thambui** [comment]
The same problem

**Comment by txeto90** [comment]
Hello, I have the same problem, somebody fixed that?
