### ISSUE TITLE
Runtime issue : Service not registered: com.google.android.gms.measurement.internal.zzjp

### ISSUE THREAD

**Issue by QuentinFarizon** [dpa99c/cordova-plugin-firebasex#562]
First of all, thanks for your awesome work on this plugin !

# Bug report

**CHECKLIST**
- [X] I have read the [issue reporting guidelines](https://github.com/dpa99c/cordova-plugin-firebasex#reporting-issues)

- [X] I confirm this is a suspected bug or issue that will affect other users

**Current behavior:**

I get a message in console :
W/ConnectionTracker: Exception thrown while unbinding
    java.lang.IllegalArgumentException: Service not registered: com.google.android.gms.measurement.internal.zzjp@53d4ad0
        at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1573)
        at android.app.ContextImpl.unbindService(ContextImpl.java:1692)
        at android.content.ContextWrapper.unbindService(ContextWrapper.java:717)
        at com.google.android.gms.common.stats.ConnectionTracker.zza(com.google.android.gms:play-services-basement@@17.3.0:55)
        at com.google.android.gms.common.stats.ConnectionTracker.unbindService(com.google.android.gms:play-services-basement@@17.3.0:50)
        at com.google.android.gms.measurement.internal.zziv.zzag(com.google.android.gms:play-services-measurement-impl@@17.5.0:245)
        at com.google.android.gms.measurement.internal.zziv.zzal(com.google.android.gms:play-services-measurement-impl@@17.5.0:262)
        at com.google.android.gms.measurement.internal.zziv.zzc(com.google.android.gms:play-services-measurement-impl@@17.5.0:336)
        at com.google.android.gms.measurement.internal.zziu.zza(com.google.android.gms:play-services-measurement-impl@@17.5.0:2)
        at com.google.android.gms.measurement.internal.zzai.run(com.google.android.gms:play-services-measurement-impl@@17.5.0:7)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at com.google.android.gms.measurement.internal.zzfy.run(com.google.android.gms:play-services-measurement-impl@@17.5.0:21)

According to this : https://github.com/firebase/firebase-android-sdk/issues/1662 it's due to the version of libraries used in this plugin. I haven't tried changing them using configuration because this plugin does not refer to the same dependencies (eg play-services-analytics) so I don't know which dependencies cause the issue.

**Steps to reproduce:**

I get that on all phones I tested with. Not sure if/what functionnalities this impact, but I'm under impression that not all analytics from my clients appear in Firebase Analytics. 

**Environment information**

- Cordova CLI version 9.0.0
- Cordova platform version android 9.0
- Plugins & versions installed in project (including this plugin)
    cordova-clipboard 1.3.0 "Clipboard"
cordova-install-referrer-api 0.1.5 "Cordova Install Referrer API"
cordova-plugin-androidx-adapter 1.1.1 "cordova-plugin-androidx-adapter"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-badge 0.8.8 "Badge"
cordova-plugin-ble-central 1.2.5 "BLE"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-dialogs 2.0.2 "Notification"
cordova-plugin-enable-multidex 0.2.0 "Enable Multidex"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-file-transfer 1.7.2-dev "File Transfer"
cordova-plugin-firebasex 11.0.3-cli "Google Firebase Plugin"
cordova-plugin-inappbrowser 4.0.0 "InAppBrowser"
cordova-plugin-ionic 5.4.7 "cordova-plugin-ionic"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 5.0.0 "cordova-plugin-ionic-webview"
cordova-plugin-market 1.2.0 "Market"
cordova-plugin-package-json-guard 1.0.1 "Package.json Guard"
cordova-plugin-safariviewcontroller 1.6.0 "SafariViewController"
cordova-plugin-splashscreen 5.0.4 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-plugin-x-toast 2.7.2 "Toast"
cordova-sqlite-storage 5.0.0 "Cordova sqlite storage plugin - cordova-sqlite-storage plugin version"
cordova.plugins.diagnostic 6.0.2 "Diagnostic"
ionic-plugin-deeplinks 1.0.20 "Ionic Deeplink Plugin"

- Dev machine OS and version :
    - Ubuntu 20.4
        
_Runtime issue_
- Device details
    - Sony Xperia XZ1 compact 
- OS details:
    - Android 9.0

_Android build issue:_	
- Node JS version
    - 12.19.0
- Gradle version
	- 6.5
- Target Android SDK version
	- 29
- Android SDK details
	- `sdkmanager --list | sed -e '/Available Packages/q'`

**Other information:**

See https://github.com/firebase/firebase-android-sdk/issues/1662

**Comment by barryvdh** [comment]
From https://cordova.apache.org/announcements/2020/06/29/cordova-android-9.0.0.html

> To use Google APIs or Firebase services, the Gradle plugin Google Services is required to be enabled when building your Android application.
> For plugin developers, this can be enabled by setting to the app's config.xml the GradlePluginGoogleServicesEnabled preference flag. From the plugin.xml file, you can do this by adding the following lines:
```xml
<config-file target="config.xml" parent="/*">
    <preference name="GradlePluginGoogleServicesEnabled" value="true" />
    <preference name="GradlePluginGoogleServicesVersion" value="4.2.0" />
</config-file>
```

Does that take care of https://firebase.google.com/docs/android/setup#add-sdks perhaps?

**Comment by QuentinFarizon** [comment]
I tried adding these 2 lines, I still got the crash
