### ISSUE TITLE
Android: App crashes are being caused when checking if Crashlytics is enabled

### ISSUE THREAD

**Issue by dpa99c** [dpa99c/cordova-plugin-firebasex#648]
# Bug report

**CHECKLIST**
- [x] I have read the [issue reporting guidelines](https://github.com/dpa99c/cordova-plugin-firebasex#reporting-issues)

- [x] I confirm this is a suspected bug or issue that will affect other users

- [x] I have reproduced the issue using the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) or provided the necessary information to reproduce the issue.

- [x] I have read [the documentation](https://github.com/dpa99c/cordova-plugin-firebasex) thoroughly and it does not help solve my issue.

- [x] I have checked that no similar issues (open or closed) already exist.

**Current behavior:**
Crashlytics is reporting app crashes caused by this plugin when it is checking if Crashlytics is enabled prior to logging an exception.

**Expected behavior:**
Checking whether Crashlytics is enabled should not cause a  native app crash

**Crash stack trace:**

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.SharedPreferences android.app.Activity.getSharedPreferences(java.lang.String, int)' on a null object reference
       at org.apache.cordova.firebase.FirebasePlugin.getPreference(FirebasePlugin.java:2820)
       at org.apache.cordova.firebase.FirebasePlugin.isCrashlyticsEnabled(FirebasePlugin.java:1894)
       at org.apache.cordova.firebase.FirebasePlugin.logExceptionToCrashlytics(FirebasePlugin.java:3031)
       at org.apache.cordova.firebase.FirebasePlugin.access$1300(FirebasePlugin.java:115)
       at org.apache.cordova.firebase.FirebasePlugin$11.run(FirebasePlugin.java:784)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)
```

**Comment by kartikthakur2022** [comment]
Hi, is this released? which version should I use? Because I started getting the same issue reported in firebase crashanytics and play console crash report. I have this in config file <plugin name="cordova-plugin-firebasex" spec="latest" />
