### ISSUE TITLE
Crash at init on Android with version 13.0.1 

### ISSUE THREAD

**Issue by QuentinFarizon** [dpa99c/cordova-plugin-firebasex#655]
# Bug report

**CHECKLIST**
- [x] I have read the [issue reporting guidelines](https://github.com/dpa99c/cordova-plugin-firebasex#reporting-issues)

- [x] I confirm this is a suspected bug or issue that will affect other users

- [ ] I have reproduced the issue using the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) or provided the necessary information to reproduce the issue.

- [x] I have read [the documentation](https://github.com/dpa99c/cordova-plugin-firebasex) thoroughly and it does not help solve my issue.

- [x] I have checked that no similar issues (open or closed) already exist.

**Current behavior:**

App crashes at start (on both devices and emulators) :

```
--------- beginning of crash
08-12 10:38:44.934 24583 24583 E AndroidRuntime: FATAL EXCEPTION: main
08-12 10:38:44.934 24583 24583 E AndroidRuntime: Process: com.boks.app.preprod, PID: 24583
08-12 10:38:44.934 24583 24583 E AndroidRuntime: java.lang.NoSuchMethodError: No direct method <init>(Lcom/google/firebase/FirebaseApp;Lcom/google/firebase/iid/Metadata;Lcom/google/firebase/platforminfo/UserAgentPublisher;Lcom/google/firebase/heartbeatinfo/HeartBeatInfo;Lcom/google/firebase/installations/FirebaseInstallationsApi;)V in class Lcom/google/firebase/iid/GmsRpc; or its super classes (declaration of 'com.google.firebase.iid.GmsRpc' appears in base.apk!classes2.dex)
08-12 10:38:44.934 24583 24583 E AndroidRuntime: 	at com.google.firebase.messaging.TopicsSubscriber.createInstance(com.google.firebase:firebase-messaging@@20.3.0:1)
08-12 10:38:44.934 24583 24583 E AndroidRuntime: 	at com.google.firebase.messaging.FirebaseMessaging.<init>(com.google.firebase:firebase-messaging@@20.3.0:12)
08-12 10:38:44.934 24583 24583 E AndroidRuntime: 	at com.google.firebase.messaging.FirebaseMessagingRegistrar.lambda$getComponents$0$FirebaseMessagingRegistrar(com.google.firebase:firebase-messaging@@20.3.0:25)
08-12 10:38:44.934 24583 24583 E AndroidRuntime: 	at com.google.firebase.messaging.FirebaseMessagingRegistrar$$Lambda$0.create(Unknown Source:0)
08-12 10:38:44.934 24583 24583 E AndroidRuntime: 	at com.google.firebase.components.ComponentRuntime.lambda$discoverComponents$0$ComponentRuntime(ComponentRuntime.java:132)
08-12 10:38:44.934 24583 24583 E AndroidRuntime: 	at com.google.firebase.components.-$$Lambda$ComponentRuntime$CLI-XObGztS2iu7RD22eoA3PpJU.get(Unknown Source:4)
08-12 10:38:44.934 24583 24583 E AndroidRuntime: 	at com.google.firebase.components.Lazy.get(Lazy.java:53)
08-12 10:38:44.934 24583 24583 E AndroidRuntime: 	at com.google.firebase.components.ComponentRuntime.doInitializeEagerComponents(ComponentRuntime.java:291)
08-12 10:38:44.934 24583 24583 E AndroidRuntime: 	at com.google.firebase.components.ComponentRuntime.initializeEagerComponents(ComponentRuntime.java:281)
08-12 10:38:44.934 24583 24583 E AndroidRuntime: 	at com.google.firebase.FirebaseApp.initializeAllApis(FirebaseApp.java:584)
08-12 10:38:44.934 24583 24583 E AndroidRuntime: 	at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:303)
08-12 10:38:44.934 24583 24583 E AndroidRuntime: 	at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:267)
08-12 10:38:44.934 24583 24583 E AndroidRuntime: 	at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:252)
08-12 10:38:44.934 24583 24583 E AndroidRuntime: 	at com.google.firebase.provider.FirebaseInitProvider.onCreate(FirebaseInitProvider.java:51)
08-12 10:38:44.934 24583 24583 E AndroidRuntime: 	at android.content.ContentProvider.attachInfo(ContentProvider.java:2092)
08-12 10:38:44.934 24583 24583 E AndroidRuntime: 	at android.content.ContentProvider.attachInfo(ContentProvider.java:2066)
08-12 10:38:44.934 24583 24583 E AndroidRuntime: 	at com.google.firebase.provider.FirebaseInitProvider.attachInfo(FirebaseInitProvider.java:45)
08-12 10:38:44.934 24583 24583 E AndroidRuntime: 	at android.app.ActivityThread.installProvider(ActivityThread.java:6983)
08-12 10:38:44.934 24583 24583 E AndroidRuntime: 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6528)
08-12 10:38:44.934 24583 24583 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6445)
08-12 10:38:44.934 24583 24583 E AndroidRuntime: 	at android.app.ActivityThread.access$1300(ActivityThread.java:219)
08-12 10:38:44.934 24583 24583 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
08-12 10:38:44.934 24583 24583 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
08-12 10:38:44.934 24583 24583 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
08-12 10:38:44.934 24583 24583 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
08-12 10:38:44.934 24583 24583 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-12 10:38:44.934 24583 24583 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
08-12 10:38:44.934 24583 24583 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

```

**Environment information**

- Cordova CLI version 
	- 10.0.0
- Cordova platform version
	- cordova-android 9.1.0 and 10.0.1
- Plugins & versions installed in project (including this plugin)
    - cordova-plugin-firebasex 13.0.1
- Dev machine OS and version, e.g.
    - OSX
        - Xcode 12.1.x, on macOS 10.15.6 (Catalina)

        
_Runtime issue_
- Device details
    - tested on Pixel emulator, Pixel 3, and Samsung 10
- OS details
    - Android 9, 10
	
Thanks for your input !

**Comment by QuentinFarizon** [comment]
Sorry, I needed to update the dependencies in my package.json by removing them and re-building
