### ISSUE TITLE
Pod error during plugin install

### ISSUE THREAD

**Issue by rolinger** [dpa99c/cordova-plugin-firebasex#673]
Hi Dave, getting a pod error during firebasex install that I don't understand

# Bug report

**CHECKLIST**
- [x ] I have read the [issue reporting guidelines](https://github.com/dpa99c/cordova-plugin-firebasex#reporting-issues)

- [ ] I confirm this is a suspected bug or issue that will affect other users

- [ ] I have reproduced the issue using the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) or provided the necessary information to reproduce the issue.

- [x ] I have read [the documentation](https://github.com/dpa99c/cordova-plugin-firebasex) thoroughly and it does not help solve my issue.

- [x ] I have checked that no similar issues (open or closed) already exist.

Prior to adding the plugin, I ensured my cocoapod was updated:

**Error:**

```
onic cordova plugin add cordova-plugin-firebasex@latest-cli --verbose
  ionic:lib Terminal info: { ci: false, shell: '/bin/zsh', tty: true, windows: false } +0ms
  ionic:lib CLI global options: { _: [ 'cordova', 'plugin', 'add', 'cordova-plugin-firebasex@latest-cli' ], help: null, h: null, verbose: true, quiet: null, interactive: true, color: true, confirm: null, json: null, project: null, '--': [] } +3ms
  ionic:lib:project Project type from config: Ionic 1 (ionic1) +0ms
  ionic:lib:project Project details: { context: 'app', type: 'ionic1', errors: [], configPath: '/Users/rpo/dev/MyCoolApp/ionic.config.json' } +0ms
  ionic Context: { binPath: '/Users/rpo/.nvm/versions/node/v14.18.1/lib/node_modules/@ionic/cli/bin/ionic', libPath: '/Users/rpo/.nvm/versions/node/v14.18.1/lib/node_modules/@ionic/cli', execPath: '/Users/rpo/dev/MyCoolApp', version: '6.17.1' } +0ms
  ionic:lib:integrations:cordova:config Loading Cordova Config (config.xml: '/Users/rpo/dev/MyCoolApp/config.xml', package.json: '/Users/rpo/dev/MyCoolApp/package.json') +0ms
> cordova plugin add cordova-plugin-firebasex@latest-cli --verbose
  ionic:lib:telemetry Sending telemetry for command: 'ionic cordova plugin' [
  ionic:lib:telemetry   'add',
  ionic:lib:telemetry   'cordova-plugin-firebasex@latest-cli',
  ionic:lib:telemetry   '--verbose',
  ionic:lib:telemetry   '--interactive',
  ionic:lib:telemetry   '--color'
  ionic:lib:telemetry ] +0ms
No scripts found for hook "before_plugin_add".
Calling plugman.fetch on plugin "cordova-plugin-firebasex@latest-cli"
fetch: Installing cordova-plugin-firebasex@latest-cli to /Users/rpo/dev/MyCoolApp
Running command: npm install cordova-plugin-firebasex@latest-cli --save-dev
Command finished with error code 0: npm install,cordova-plugin-firebasex@latest-cli,--save-dev
Copying plugin "/Users/rpo/dev/MyCoolApp/node_modules/cordova-plugin-firebasex" => "/Users/rpo/dev/MyCoolApp/plugins/cordova-plugin-firebasex"
Calling plugman.install on plugin "/Users/rpo/dev/MyCoolApp/plugins/cordova-plugin-firebasex" for platform "ios
Installing "cordova-plugin-firebasex" for ios
Finding scripts for "before_plugin_install" hook from plugin cordova-plugin-firebasex on ios platform only.
Executing script found in plugin cordova-plugin-firebasex for hook "before_plugin_install": plugins/cordova-plugin-firebasex/scripts/ios/before_plugin_install.js
Install start for "cordova-plugin-firebasex" on ios.
Loaded API for ios project /Users/rpo/dev/MyCoolApp/platforms/ios/cordova/Api.js
Beginning processing of action stack for ios project...
Adding non-custom framework to project... AuthenticationServices.framework -> {"customFramework":false,"embed":false,"link":true,"weak":false}
Non-custom framework added to project. AuthenticationServices.framework -> {"customFramework":false,"link":true,"weak":false}
Action stack processing complete.
pods.json found in platforms/ios
Podfile found in platforms/ios
Adding pods since the plugin contained <podspecs>
Set pods.json for `declarations` - `use_frameworks!`
Added declaration line for `use_frameworks!`
Set pods.json for `sources` - `https://cdn.cocoapods.org/`
Added source line for `https://cdn.cocoapods.org/`
Set pods.json for `libraries` - `Firebase/Core`
Added pod line for `Firebase/Core`
Set pods.json for `libraries` - `Firebase/Auth`
Added pod line for `Firebase/Auth`
Set pods.json for `libraries` - `Firebase/Messaging`
Added pod line for `Firebase/Messaging`
Set pods.json for `libraries` - `Firebase/Performance`
Added pod line for `Firebase/Performance`
Set pods.json for `libraries` - `Firebase/RemoteConfig`
Added pod line for `Firebase/RemoteConfig`
Set pods.json for `libraries` - `FirebaseFirestore`
Added pod line for `FirebaseFirestore`
Set pods.json for `libraries` - `Firebase/Crashlytics`
Added pod line for `Firebase/Crashlytics`
Set pods.json for `libraries` - `Firebase/Functions`
Added pod line for `Firebase/Functions`
Set pods.json for `libraries` - `Firebase/Installations`
Added pod line for `Firebase/Installations`
Set pods.json for `libraries` - `GoogleSignIn`
Added pod line for `GoogleSignIn`
Wrote to pods.json.
Wrote to Podfile.
Running `pod install` (to install plugins)
Running command: pod --version
Command finished with error code 0: pod --version
Running command: pod install --verbose
==== pod install start ====

  Preparing

Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods-AttendaGo`: (``)

Finding Podfile changes
  A Firebase
  A FirebaseFirestore
  A GoogleSignIn

Fetching external sources
-> Pre-downloading: `FirebaseFirestore` from `https://github.com/invertase/firestore-ios-sdk-frameworks.git`, tag `8.4.0`
  > Copying FirebaseFirestore from `/Users/rpo/Library/Caches/CocoaPods/Pods/External/FirebaseFirestore/51c8c6f325156c8a5d5f7966997e7115` to `Pods/FirebaseFirestore`


Resolving dependencies of `Podfile`
  CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only performed in repo update
  CDN: trunk Relative path: all_pods_versions_0_3_5.txt exists! Returning local because checking is only performed in repo update
  CDN: trunk Relative path: Specs/0/3/5/Firebase/8.8.0/Firebase.podspec.json exists! Returning local because checking is only performed in repo update
  CDN: trunk Relative path: Specs/0/3/5/Firebase/8.4.0/Firebase.podspec.json exists! Returning local because checking is only performed in repo update
  CDN: trunk Relative path: Specs/0/3/5/Firebase/8.4.0/Firebase.podspec.json exists! Returning local because checking is only performed in repo update
  CDN: trunk Relative path: Specs/0/3/5/Firebase/8.4.0/Firebase.podspec.json exists! Returning local because checking is only performed in repo update
  CDN: trunk Relative path: Specs/0/3/5/Firebase/8.4.0/Firebase.podspec.json exists! Returning local because checking is only performed in repo update
  CDN: trunk Relative path: Specs/0/3/5/Firebase/8.4.0/Firebase.podspec.json exists! Returning local because checking is only performed in repo update
  CDN: trunk Relative path: Specs/0/3/5/Firebase/8.4.0/Firebase.podspec.json exists! Returning local because checking is only performed in repo update
  CDN: trunk Relative path: Specs/0/3/5/Firebase/8.4.0/Firebase.podspec.json exists! Returning local because checking is only performed in repo update
  CDN: trunk Relative path: Specs/0/3/5/Firebase/8.4.0/Firebase.podspec.json exists! Returning local because checking is only performed in repo update
  CDN: trunk Relative path: all_pods_versions_d_4_0.txt exists! Returning local because checking is only performed in repo update
  CDN: trunk Relative path: Specs/d/4/0/GoogleSignIn/6.0.2/GoogleSignIn.podspec.json exists! Returning local because checking is only performed in repo update
[!] CocoaPods could not find compatible versions for pod "FirebaseFirestore":
  In Podfile:
    FirebaseFirestore (from `https://github.com/invertase/firestore-ios-sdk-frameworks.git`, tag `8.4.0`)

Specs satisfying the `FirebaseFirestore (from `https://github.com/invertase/firestore-ios-sdk-frameworks.git`, tag `8.4.0`)` dependency were found, but they required a higher minimum deployment target.

/Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:317:in `raise_error_unless_state'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:299:in `block in unwind_for_conflict'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:297:in `tap'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:297:in `unwind_for_conflict'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:682:in `attempt_to_activate'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:254:in `process_topmost_state'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:182:in `resolve'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolver.rb:43:in `resolve'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/resolver.rb:94:in `resolve'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:1078:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:1076:in `resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:416:in `analyze'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:241:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:240:in `resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:161:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/command/install.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'

Command finished with error code 1: pod install,--verbose
Failed to install 'cordova-plugin-firebasex': Error: pod: Command failed with exit code 1
    at ChildProcess.whenDone (/Users/rpo/dev/MyCoolApp/node_modules/cordova-common/src/superspawn.js:136:25)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1058:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
pod: Command failed with exit code 1
Error: pod: Command failed with exit code 1
    at ChildProcess.whenDone (/Users/rpo/dev/MyCoolApp/node_modules/cordova-common/src/superspawn.js:136:25)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1058:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
[ERROR] An error occurred while running subprocess cordova.
        
        cordova plugin add cordova-plugin-firebasex@latest-cli --verbose exited with exit code 1.
        
        Re-running this command with the --verbose flag may provide more information.
  ionic:utils-process onBeforeExit handler: 'process.exit' received +0ms
  ionic:utils-process onBeforeExit handler: running 1 functions +0ms
  ionic:utils-process processExit: exiting (exit code: 1) +26ms
```

Then when I try to install it manually, I get:

```
pod 'FirebaseFirestore', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag => '8.4.0' 

zsh: no such file or directory: https://github.com/invertase/firestore-ios-sdk-frameworks.git,
```

I inquired with the developer of the `Firestore` pod here, https://github.com/invertase/firestore-ios-sdk-frameworks/issues/35

And he is saying the PodFile needs to specify a minimum iOS target:
```
 s.ios.deployment_target  = '10.0' 
 s.osx.deployment_target  = '10.12' 
 s.tvos.deployment_target = '10.0' 
```
But, I wasn't certain if doing so was going to cause other issues.  My current PodFile, considering its auto-generated and states "DO NOT MODIFY" I figure I need a bit more direction on this one:

# DO NOT MODIFY -- auto-generated by Apache Cordova
source 'https://cdn.cocoapods.org/'
platform :ios, '9.3'
use_frameworks!
target 'AttendaGo' do
        project 'AttendaGo.xcodeproj'
        pod 'Firebase/Core', '8.4.0'
        pod 'Firebase/Auth', '8.4.0'
        pod 'Firebase/Messaging', '8.4.0'
        pod 'Firebase/Performance', '8.4.0'
        pod 'Firebase/RemoteConfig', '8.4.0'
        pod 'FirebaseFirestore', :tag => '8.4.0', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git'
        pod 'Firebase/Crashlytics', '8.4.0'
        pod 'Firebase/Functions', '8.4.0'
        pod 'Firebase/Installations', '8.4.0'
        pod 'GoogleSignIn', '5.0.2'
end

**Comment by rolinger** [comment]
ah, went back and reread `firebasex` docs and see the minimum supported is iOS 10.  Which answers my own question of setting the podfile to minimum iOS 10 should not break anything else.

My target deployment was set to 9.3 in config.xml and in Xcode.  So, in Xcode I changed the project target deployment to 10.0, but in the Xcode workspace for `Pods`, it was set to 11.0, not certain why, but I changed that down to 10.0.  And then in my config.xml file I changed the `<preference name="deployment-target" value="10.0" />`.  

I then compiled my project from CLI again and after the PodFile still showed 9.3, so I manually edited it, then was able to successfully pull do the `pod update repo` and `pod install`.

I then removed firebasex plugin ...just before adding it again I checked the PodFile again and somehow it had auto-reset to deployment target of `11.0`.  I manually edited that back down to 10.0 again.  Reinstalled the `firebasex` plugin and this time it took with no errors.

This seemingly fixed all `FirebaseX` issues.  But during a build from CLI, it is now erroring on what appears to be another target deployment issue for the storyboard.  Gonna have to go track this one down now.

```
warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.1.99. (in target 'GoogleSignIn' from project 'Pods')
warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.1.99. (in target 'AppAuth' from project 'Pods')
** ARCHIVE FAILED **


The following build commands failed:
	CompileStoryboard /Users/rpo/dev/MyCoolApp/platforms/ios/MyCoolApp/CDVLaunchScreen.storyboard
```
