### ISSUE TITLE
Crash due to use of getAlpnSelectedProtocol on Android 11

### ISSUE THREAD

**Issue by askdaddy** [dpa99c/cordova-plugin-firebasex#695]
I got a lot of crash report in Firebase console.

the dump:
```
Fatal Exception: java.lang.AssertionError: Method getAlpnSelectedProtocol not supported for object SSL socket over Socket[address=firebaseinappmessaging.googleapis.com/172.217.160.106,port=443,localPort=45696]
       at io.grpc.okhttp.internal.OptionalMethod.invoke(OptionalMethod.java:114)
       at io.grpc.okhttp.internal.OptionalMethod.invokeWithoutCheckedException(OptionalMethod.java:135)
       at io.grpc.okhttp.OkHttpProtocolNegotiator$AndroidNegotiator.getSelectedProtocol(OkHttpProtocolNegotiator.java:183)
       at io.grpc.okhttp.OkHttpProtocolNegotiator$AndroidNegotiator.negotiate(OkHttpProtocolNegotiator.java:145)
       at io.grpc.okhttp.OkHttpTlsUpgrader.upgrade(OkHttpTlsUpgrader.java:63)
       at io.grpc.okhttp.OkHttpClientTransport$4.run(OkHttpClientTransport.java:571)
       at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)
```

then I reseash the issue found: https://github.com/grpc/grpc-java/issues/7519
seems the okhttp issue has to be fixed, plz upgrading to solve the issue.

**Comment by stickoutapp** [comment]
Thank you!
