### ISSUE TITLE
It is still impossible to install this plugin together with the mslobodan / cordova-plugin-firebase-dynamiclinks

### ISSUE THREAD

**Issue by r-rodriguez-s** [dpa99c/cordova-plugin-firebasex#722]
# Bug report

**CHECKLIST**
- [ ] I have read the [issue reporting guidelines](https://github.com/dpa99c/cordova-plugin-firebasex#reporting-issues)

- [ ] I confirm this is a suspected bug or issue that will affect other users

- [ ] I have reproduced the issue using the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) or provided the necessary information to reproduce the issue.

- [ ] I have read [the documentation](https://github.com/dpa99c/cordova-plugin-firebasex) thoroughly and it does not help solve my issue.

- [ ] I have checked that no similar issues (open or closed) already exist.

**Current behavior:**

Every plugin separated install work perfect but wen install both firebasex plugin stop with error when cordova platform add ios@6.2.0

**Expected behavior:**
no error is expected and finalized install both plugins

**Steps to reproduce:**
Add both plugins and ejecute cordova platform add ios@6.2.0

**Screenshots**

**Environment information**
Message in MAC terminal
iOS project created with cordova-ios@6.2.0
Installing "cc.fovea.cordova.purchase" for ios
Installing "cordova-custom-config" for ios
Installing "cordova-launch-review" for ios
Installing "cordova-plugin-app-version" for ios
Installing "cordova-plugin-camera" for ios
Installing "cordova-plugin-device" for ios
Installing "cordova-plugin-dialogs" for ios
Installing "cordova-plugin-file" for ios
Installing "cordova-plugin-firebase-analytics" for ios
Running command: pod install --verbose

[!] Your project does not explicitly specify the CocoaPods master specs repo. Since CDN is now used as the default, you may safely remove it from your repos directory via `pod repo remove master`. To suppress this warning please add `warn_for_unused_master_specs_repo => false` to your Podfile.

Installing "cordova-plugin-firebase-dynamiclinks" for ios
Plugin dependency "cordova-plugin-firebase-analytics@6.1.0" already fetched, using that version.
Dependent plugin "cordova-plugin-firebase-analytics" already installed on ios.
Running command: pod install --verbose

[!] Your project does not explicitly specify the CocoaPods master specs repo. Since CDN is now used as the default, you may safely remove it from your repos directory via `pod repo remove master`. To suppress this warning please add `warn_for_unused_master_specs_repo => false` to your Podfile.

Installing "cordova-plugin-firebasex" for ios
Running command: pod install --verbose
Failed to install 'cordova-plugin-firebasex': Error: pod: Command failed with exit code 31
    at ChildProcess.whenDone (/Users/mercedescaballerogarcia/Documents/Desarrollo/app-facetoned/app-facetoned-2022-b/app-facetoned/cordova_ios/platforms/ios/cordova/node_modules/cordova-common/src/superspawn.js:136:25)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1058:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:400:28)
    at Pipe.<anonymous> (net.js:686:12)
pod: Command failed with exit code 31

- Cordova CLI version 
	- 10.0.0 (cordova-lib@10.1.0)

- Cordova platform version
	- Available platforms: 
  android ^9.1.0
  browser ^6.0.0
  electron ^1.1.1
  ios ^6.2.0
  osx ^6.0.0

- Plugins & versions installed in project (including this plugin)

cc.fovea.cordova.purchase 10.5.3 "Purchase"
cordova-custom-config 5.1.0 "cordova-custom-config"
cordova-launch-review 3.1.1 "Launch Review"
cordova-plugin-app-version 0.1.12 "AppVersion"
cordova-plugin-camera 4.1.0 "Camera"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-dialogs 2.0.2 "Notification"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-firebase-dynamiclinks 6.1.3 "FirebaseDynamicLinksPlugin"
cordova-plugin-firebasex 14.0.0 "Google Firebase Plugin"
cordova-plugin-fullscreen 1.3.0 "cordova-plugin-fullscreen"
cordova-plugin-network-information 3.0.0 "Network Information"
cordova-plugin-screen-orientation 3.0.2 "Screen Orientation"
cordova-plugin-spinnerdialog 1.3.2 "SpinnerDialog"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-streaming-media 2.3.0 "StreamingMedia"
cordova-plugin-whitelist 1.3.5 "Whitelist"
es6-promise-plugin 4.2.2 "Promise"

- Dev machine OS and version, e.g.
    - OSX
    Monterey. V 12.3
Xcode Version 13.3 (13E113)
        
_Runtime issue_

- OS details
   only en while generating ios platform y Android all is working as spected
	
_
	
_iOS build issue:_
- Node JS version v14.19.1

**Other information:**
Do you plan to support firebasex to be able to use dynamic linkcs without having to use other plugins external to firebasex?

Thanks in advance

**Comment by malk90** [comment]
hi, i have this problem
