### ISSUE TITLE
App crash using Cordova 11.0.0 

### ISSUE THREAD

**Issue by jomorr-jkl** [dpa99c/cordova-plugin-firebasex#748]
# Bug report

**CHECKLIST**
- [X] I have read the [issue reporting guidelines](https://github.com/dpa99c/cordova-plugin-firebasex#reporting-issues)

- [X] I confirm this is a suspected bug or issue that will affect other users

- [ ] I have reproduced the issue using the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) or provided the necessary information to reproduce the issue.

- [X] I have read [the documentation](https://github.com/dpa99c/cordova-plugin-firebasex) thoroughly and it does not help solve my issue.

- [X] I have checked that no similar issues (open or closed) already exist.

**Current behavior:**

Running a compiled app crashes upon startup.

**Expected behavior:**
App starts up and runs without crashing.

**Steps to reproduce:**
create an Android apk, sideload onto a device and launch the app.  Also compiling in Android Studio to run on a device crashes.

**Screenshots**
N/A

**Environment information**

- Cordova CLI version 
	- `cordova -v`
11.0.0

- Cordova platform version
	- `cordova platform ls`
Installed platforms:
  android 11.0.0
  ios 6.2.0
Available platforms:
  browser ^6.0.0
  electron ^3.0.0
  osx ^6.0.0

- Plugins & versions installed in project (including this plugin)
    - `cordova plugin ls`
cordova-open-native-settings 1.5.5 "Native settings"
cordova-plugin-androidx-adapter 1.1.3 "cordova-plugin-androidx-adapter"
cordova-plugin-androidx 1.0.2 "cordova-plugin-androidx"
cordova-plugin-background-upload 1.1.0 "Cordova Background Upload Plugin"
cordova-plugin-camera 6.0.0 "Camera"
cordova-plugin-canvas2image-updated 1.2.0 "Canvas 2 Image"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-customurlscheme 5.0.2 "Custom URL scheme"
cordova-plugin-device 2.1.0 "Device"
cordova-plugin-dialogs 2.0.2 "Notification"
cordova-plugin-email-composer 0.10.1 "EmailComposer"
cordova-plugin-file 7.0.0 "File"
cordova-plugin-firebasex 14.2.0 "Google Firebase Plugin"
cordova-plugin-inappbrowser 5.0.0 "InAppBrowser"
cordova-plugin-network-information 3.0.0 "Network Information"
cordova-plugin-screen-orientation 3.0.2 "Screen Orientation"
cordova-plugin-statusbar 3.0.0 "StatusBar"
cordova-plugin-streaming-media 2.3.0 "StreamingMedia"
cordova-plugin-video-editor 1.1.3 "VideoEditor"
cordova-plugin-wkwebview-file-xhr 3.1.0 "Cordova WKWebView File XHR Plugin"
es6-promise-plugin 4.2.2 "Promise"

- Dev machine OS and version, e.g.
    - OSX
        - `sw_vers`
ProductName:    macOS
ProductVersion: 11.6.7
BuildVersion:   20G630

    - Windows 10
        - `winver`
OS Build 25163.1000
        
_Runtime issue_
- Device details
Samsung Galaxy S21, Pixel XL Virtual Device

- OS details
    - _Android 12
	
_Android build issue:_	
- Node JS version
    - `node -v`
v12.14.0

- Gradle version
	- `ls platforms/android/.gradle`
6.0.1                   7.4.2                   buildOutputCleanup      vcs-1

- Target Android SDK version
	- `android:targetSdkVersion` in `AndroidManifest.xml`
32

- Android SDK details
	- `sdkmanager --list | sed -e '/Available Packages/q'`
	
**Related code:**
```
insert any relevant code here such as plugin API calls / input parameters
```

**Console output**
<details>
<summary>console output</summary>

```

// Paste any relevant JS/native console output here
2022-07-20 13:07:52.152 9228-9501/com.nwbbateam E/AndroidRuntime: FATAL EXCEPTION: pool-33-thread-1
    Process: com.nwbbateam, PID: 9228
    java.lang.ExceptionInInitializerError
        at okhttp3.internal.platform.Platform.get(Platform.java:85)
        at okhttp3.OkHttpClient.newSslSocketFactory(OkHttpClient.java:263)
        at okhttp3.OkHttpClient.<init>(OkHttpClient.java:229)
        at okhttp3.OkHttpClient.<init>(OkHttpClient.java:202)
        at com.google.firebase.functions.FirebaseFunctions.<init>(FirebaseFunctions.java:94)
        at com.google.firebase.functions.FunctionsMultiResourceComponent.get(FunctionsMultiResourceComponent.java:49)
        at com.google.firebase.functions.FirebaseFunctions.getInstance(FirebaseFunctions.java:171)
        at com.google.firebase.functions.FirebaseFunctions.getInstance(FirebaseFunctions.java:198)
        at org.apache.cordova.firebase.FirebasePlugin$1.run(FirebasePlugin.java:189)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)
     Caused by: java.lang.IllegalStateException: Expected Android API level 21+ but was 31
        at okhttp3.internal.platform.AndroidPlatform.buildIfSupported(AndroidPlatform.java:238)
        at okhttp3.internal.platform.Platform.findPlatform(Platform.java:202)
        at okhttp3.internal.platform.Platform.<clinit>(Platform.java:79)
        at okhttp3.internal.platform.Platform.get(Platform.java:85) 
        at okhttp3.OkHttpClient.newSslSocketFactory(OkHttpClient.java:263) 
        at okhttp3.OkHttpClient.<init>(OkHttpClient.java:229) 
        at okhttp3.OkHttpClient.<init>(OkHttpClient.java:202) 
        at com.google.firebase.functions.FirebaseFunctions.<init>(FirebaseFunctions.java:94) 
        at com.google.firebase.functions.FunctionsMultiResourceComponent.get(FunctionsMultiResourceComponent.java:49) 
        at com.google.firebase.functions.FirebaseFunctions.getInstance(FirebaseFunctions.java:171) 
        at com.google.firebase.functions.FirebaseFunctions.getInstance(FirebaseFunctions.java:198) 
        at org.apache.cordova.firebase.FirebasePlugin$1.run(FirebasePlugin.java:189) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:920) 
```

</details><br/><br/>

**Other information:**

Possibly an issue with okHTTP: https://stackoverflow.com/questions/63917431/expected-android-api-level-21-but-was-30

**Comment by Clevero** [comment]
Could you resolve this issue?

**Comment by jomorr-jkl** [comment]
No, I disabled push notifications in my new app version.  I just added this plugin back in and it is still crashing.  I am going to try to build the sample app to confirm if it is my app or not.

**Comment by Clevero** [comment]
I finally could resolve this issue on my side. I had some options for the cordova-plugin-firebasex setup in my package.json
![grafik](https://user-images.githubusercontent.com/6106081/191779009-35521888-ca5d-49e6-9c0d-6f82b66b5dc4.png)

I deleted the marked section, recompiled and the app did not crash at the start. Tested on a real device
