### ISSUE TITLE
16.3.0 issue on IOS Compilation

### ISSUE THREAD

**Issue by bandeto45** [dpa99c/cordova-plugin-firebasex#852]
From your latest version 16.3.0 there is an error showing during compiling on IOS. 
```

CocoaPods could not find compatible versions for pod "FirebaseInAppMessaging":
  In Podfile:
    FirebaseInAppMessaging (= 10.17.0-beta)

None of your spec sources contain a spec satisfying the dependency: `FirebaseInAppMessaging (= 10.17.0-beta)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

/Users/dxb/.gem/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:317:in `raise_error_unless_state'
/Users/dxb/.gem/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:299:in `block in unwind_for_conflict'
/Users/dxb/.gem/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:297:in `tap'
/Users/dxb/.gem/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:297:in `unwind_for_conflict'
/Users/dxb/.gem/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:257:in `process_topmost_state'
/Users/dxb/.gem/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:182:in `resolve'
/Users/dxb/.gem/gems/molinillo-0.8.0/lib/molinillo/resolver.rb:43:in `resolve'
/Users/dxb/.gem/gems/cocoapods-1.14.3/lib/cocoapods/resolver.rb:94:in `resolve'
/Users/dxb/.gem/gems/cocoapods-1.14.3/lib/cocoapods/installer/analyzer.rb:1082:in `block in resolve_dependencies'
/Users/dxb/.gem/gems/cocoapods-1.14.3/lib/cocoapods/user_interface.rb:64:in `section'
/Users/dxb/.gem/gems/cocoapods-1.14.3/lib/cocoapods/installer/analyzer.rb:1080:in `resolve_dependencies'
/Users/dxb/.gem/gems/cocoapods-1.14.3/lib/cocoapods/installer/analyzer.rb:125:in `analyze'
/Users/dxb/.gem/gems/cocoapods-1.14.3/lib/cocoapods/installer.rb:422:in `analyze'
/Users/dxb/.gem/gems/cocoapods-1.14.3/lib/cocoapods/installer.rb:244:in `block in resolve_dependencies'
/Users/dxb/.gem/gems/cocoapods-1.14.3/lib/cocoapods/user_interface.rb:64:in `section'
/Users/dxb/.gem/gems/cocoapods-1.14.3/lib/cocoapods/installer.rb:243:in `resolve_dependencies'
/Users/dxb/.gem/gems/cocoapods-1.14.3/lib/cocoapods/installer.rb:162:in `install!'
/Users/dxb/.gem/gems/cocoapods-1.14.3/lib/cocoapods/command/install.rb:52:in `run'
/Users/dxb/.gem/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/Users/dxb/.gem/gems/cocoapods-1.14.3/lib/cocoapods/command.rb:52:in `run'
/Users/dxb/.gem/gems/cocoapods-1.14.3/bin/pod:55:in `<top (required)>'
/Users/dxb/.gem/bin/pod:25:in `load'
/Users/dxb/.gem/bin/pod:25:in `<main>'
```

**Comment by dpa99c** [comment]
You have not filled out the issue template so have provided insufficient information therefore this issue will be closed as invalid.

Please follow the [documented steps](https://github.com/dpa99c/cordova-plugin-firebasex?tab=readme-ov-file#reporting-a-bug-or-problem) for reporting an issue.

If you are able to reproduce the issue in the example project, please open a new issue and fill out the issue template in full, including steps to reproduce in the example project and details of test devices used to reproduce the issue.

In your case in particular, make sure you have the latest version of Cocopods installed and your local repo is up-to-date by running `pod repo update`
